# Generated by Django 2.1.1 on 2018-09-19 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('address', models.CharField(max_length=64)),
                ('amount', models.IntegerField(default=0)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Waiting'), (2, 'Confirmed')], default=0)),
                ('tx', models.CharField(blank=True, default='', max_length=64, null=True)),
            ],
            options={
                'ordering': ('created',),
                'get_latest_by': 'created',
            },
        ),
    ]
