"""
Django settings for cointap project.

Generated by 'django-admin startproject' using Django 1.11.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("COINTAP_SECRET_KEY", 'q$7od+7el%uv8*=%vifcd_k+@yx%!zja=crg^u5=!sft8pqkwx')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool(os.environ.get("COINTAP_DEBUG"))

ALLOWED_HOSTS = []

ALLOWED_HOSTS.append(os.environ.get("COINTAP_ALLOWED_HOSTS", "cointap.merkleblock.com"))

STATIC_ROOT = os.environ.get("COINTAP_STATIC_ROOT", os.path.join(BASE_DIR, "static"))

STATIC_URL = '/static/'

MEDIA_ROOT = os.environ.get("COINTAP_MEDIA_ROOT", os.path.join(BASE_DIR, "media"))

MEDIA_URL = os.environ.get("COINTAP_MEDIA_URL", "/media/")

COIN_NAME = os.environ.get("COINTAP_COIN_NAME", "Handshake")

COIN_PARAMS = os.environ.get("COINTAP_COIN_PARAMS", "testnet")

COIN_NODE = os.environ.get("COINTAP_COIN_NODE", "http://127.0.0.1:13039")

COIN_WALLET = os.environ.get("COINTAP_WALLET", "primary")

COIN_AUTH = tuple(os.environ.get("COINTAP_COIN_AUTH", "x:bikeshed").split(":"))

COIN_SHARE = float(os.environ.get("COIN_SHARE", 1e-5))

COIN_FEE = float(os.environ.get("COINTAP_COIN_FEE", 1000))

HTML_FILES = "html"

CORS_ORIGIN_ALLOW_ALL = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'corsheaders',

    'django_extensions',
    'webpack_loader',

    'faucet'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'cointap.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cointap.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ]
}

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'assets'),
    os.path.join(BASE_DIR, 'media'),
)

WEBPACK_LOADER = {
    "DEFAULT": {
        "BUNDLE_DIR_NAME": "dist/",
        "STATS_FILE": os.path.join(BASE_DIR, "webpack-stats.json"),
    }
}
